# Generated by Django 3.0.4 on 2020-03-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_subject', models.CharField(max_length=100)),
                ('ticket_body', models.TextField()),
                ('ticket_user', models.CharField(max_length=100)),
                ('ticket_created', models.DateField()),
            ],
        ),
    ]
