# Generated by Django 3.0.4 on 2020-03-10 09:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
