# Generated by Django 3.0.4 on 2020-03-10 12:30

import apps.ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20200310_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=apps.ticketing.models.random_string, max_length=100, primary_key=True, serialize=False),
        ),
    ]
